name: etag
description: Create simple HTTP ETags.
version: 1.0.0
homepage: https://github.com/Hexer10/etag

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  crypto: ^3.0.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8


